"""Add user, project, and mission tables

Revision ID: 007be02b5efa
Revises: 35ca091b40e7
Create Date: 2024-12-14 17:18:05.193735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007be02b5efa'
down_revision: Union[str, None] = '35ca091b40e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
