"""Add main job to users

Revision ID: 092b6502ca77
Revises: 862bbe12d193
Create Date: 2025-02-26 14:19:21.875449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092b6502ca77'
down_revision: Union[str, None] = '862bbe12d193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('main_job', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'main_job')
    # ### end Alembic commands ###
