"""Add creation_date to pricing

Revision ID: 0abf41b6caa0
Revises: 23029b999b59
Create Date: 2024-12-18 12:05:04.539427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0abf41b6caa0'
down_revision: Union[str, None] = '23029b999b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing', sa.Column('creation_date', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing', 'creation_date')
    # ### end Alembic commands ###
