"""Add handler id to projects

Revision ID: 1a81df9b04a5
Revises: 83743719a6b9
Create Date: 2025-03-12 13:45:51.872422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a81df9b04a5'
down_revision: Union[str, None] = '83743719a6b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'handler_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'handler_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
