"""Add users foreign key to pricing

Revision ID: 23029b999b59
Revises: 156367b0d190
Create Date: 2024-12-18 12:03:44.925882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23029b999b59'
down_revision: Union[str, None] = '156367b0d190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'pricing', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.drop_column('pricing', 'user_id')
    # ### end Alembic commands ###
