"""Add creation_date to roles

Revision ID: 2576a8c7fbb4
Revises: d7e4b12d4549
Create Date: 2024-12-18 11:19:54.422517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2576a8c7fbb4'
down_revision: Union[str, None] = 'd7e4b12d4549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('creation_date', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'creation_date')
    # ### end Alembic commands ###
