"""Add language field to technologies

Revision ID: 4fa9e36a11b4
Revises: 553ea0429f17
Create Date: 2024-12-18 11:49:34.246855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fa9e36a11b4'
down_revision: Union[str, None] = '553ea0429f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technologies', sa.Column('language', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technologies', 'language')
    # ### end Alembic commands ###
