"""Add creation_date to technologies

Revision ID: 553ea0429f17
Revises: e199aeb84700
Create Date: 2024-12-18 11:45:09.136864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '553ea0429f17'
down_revision: Union[str, None] = 'e199aeb84700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technologies', sa.Column('creation_date', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technologies', 'creation_date')
    # ### end Alembic commands ###
