"""Rename update field of invoices

Revision ID: 67877c7d05d6
Revises: 6c6b87e9c123
Create Date: 2025-01-20 16:41:26.846813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67877c7d05d6'
down_revision: Union[str, None] = '6c6b87e9c123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.drop_column('invoices', 'last_update')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('last_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('invoices', 'updated_at')
    # ### end Alembic commands ###
