"""Add tables

Revision ID: 6c6b87e9c123
Revises: aa43657412ca
Create Date: 2025-01-20 16:34:33.038184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c6b87e9c123'
down_revision: Union[str, None] = 'aa43657412ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('validation_status', sa.Enum('draft', 'sent', 'validated', 'rejected', 'in_edition', name='invoice_statuses'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('invoice_has_custom_block',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('custom_block_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['custom_block_id'], ['custom_blocks.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('invoice_id', 'custom_block_id')
    )
    op.create_table('invoice_infos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('expiry_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('client_address', sa.String(), nullable=False),
    sa.Column('deposit_price', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_infos')
    op.drop_table('invoice_has_custom_block')
    op.drop_table('invoices')
    op.drop_table('custom_blocks')
    # ### end Alembic commands ###
