"""Add handler id to projects

Revision ID: 83743719a6b9
Revises: 092b6502ca77
Create Date: 2025-03-12 13:39:53.683582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83743719a6b9'
down_revision: Union[str, None] = '092b6502ca77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('handler_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'projects', 'users', ['handler_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'handler_id')
    # ### end Alembic commands ###
