"""Add invoices models routes

Revision ID: 85ab6bdea8d3
Revises: 5e0e04747dc7
Create Date: 2025-01-20 15:31:28.203362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ab6bdea8d3'
down_revision: Union[str, None] = '5e0e04747dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
