"""Add blocked status to mission_statuses enum

Revision ID: 88d44c3f3f4a
Revises: 613373b37b2b
Create Date: 2024-12-18 10:58:35.338478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d44c3f3f4a'
down_revision: Union[str, None] = '613373b37b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
