"""Update date fields for invoices and invoices infos

Revision ID: d7619e5a15ab
Revises: aa07a5e6f4f3
Create Date: 2025-01-20 16:25:45.719958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7619e5a15ab'
down_revision: Union[str, None] = 'aa07a5e6f4f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
