"""Add creation_date to milestones

Revision ID: d7e4b12d4549
Revises: 88d44c3f3f4a
Create Date: 2024-12-18 11:15:56.857612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e4b12d4549'
down_revision: Union[str, None] = '88d44c3f3f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('creation_date', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestones', 'creation_date')
    # ### end Alembic commands ###
