"""Add creation_date to permissions

Revision ID: e199aeb84700
Revises: 2576a8c7fbb4
Create Date: 2024-12-18 11:32:36.793266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e199aeb84700'
down_revision: Union[str, None] = '2576a8c7fbb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('creation_date', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'creation_date')
    # ### end Alembic commands ###
