"""Update calendar modal dates

Revision ID: f3657f287186
Revises: 0b895798a357
Create Date: 2025-01-21 19:49:39.300241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3657f287186'
down_revision: Union[str, None] = '0b895798a357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availability_calendar', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('availability_calendar', sa.Column('end_date', sa.Date(), nullable=False))
    op.drop_column('availability_calendar', 'availability_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availability_calendar', sa.Column('availability_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('availability_calendar', 'end_date')
    op.drop_column('availability_calendar', 'start_date')
    # ### end Alembic commands ###
